# Generated by Django 2.0.1 on 2018-02-12 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainedFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('end_timer', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Labored_Focus',
        ),
        migrations.AddField(
            model_name='strainedfocus',
            name='timer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strained_focus', to='timer.Timer'),
        ),
    ]
